---

- name: Téléchargement de Wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  become: true

- name: Extraction du paquet Wordpress
  unarchive: 
    src: /tmp/wordpress.tar.gz 
    dest: /var/www/ 
    copy: no
  become: true

- name: Mise à jour du site par défaut de Apache
  become: true
  lineinfile:
    dest: /etc/apache2/sites-enabled/000-default.conf
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot /var/www/wordpress"
  notify:
  - restart apache

- name: Configuration du fichier wp-config.php
  template:
    src: templates/wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
  become: true
