NODES = [ 
	{:hostname => "haproxy", :ip => "192.168.33.10", :cpus => 1, :mem => 512 }, 
	{:hostname => "web1", :ip => "192.168.33.11", :cpus => 1, :mem => 512},
	{:hostname => "web2", :ip => "192.168.33.12", :cpus => 1, :mem => 512}
	]

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  NODES.each do |node| 
	config.vm.define node[:hostname] do |cfg|
		cfg.vm.hostname = node[:hostname] 
		cfg.vm.network "private_network", ip: node[:ip]
			cfg.vm.provider "virtualbox" do |v| 
				v.customize ["modifyvm", :id, "--cpus", node[:cpus] ] 
				v.customize ["modifyvm", :id, "--memory", node[:mem] ] 
				v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"] 
				v.customize ["modifyvm", :id, "--natdnsproxy1", "on"] 
				v.customize ["modifyvm", :id, "--name", node[:hostname] ] 
			end 
		end 
	end
	
	## CONFIG MACHINE HAPROXY ##
	config.vm.define "haproxy" do |haproxy|
		haproxy.vm.provision "shell", inline: <<-SHELL
			sudo yum update -y
			sudo yum install haproxy sshpass -y
		SHELL
		
		haproxy.vm.provision "file", source: "haproxy.cfg", destination: "/tmp/haproxy.cfg"
		
		haproxy.vm.provision "shell", inline: <<-SHELL
			sudo rm /etc/haproxy/haproxy.cfg
			sudo mv /tmp/haproxy.cfg /etc/haproxy/haproxy.cfg
			sudo systemctl start haproxy
			
			sudo bash -c 'echo "192.168.33.11 web1" >> /etc/hosts'
			sudo bash -c 'echo "192.168.33.12 web2" >> /etc/hosts'
			
			sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
			sudo systemctl restart sshd
			
			ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/haproxy -q -N ""
			
			sudo systemctl start firewalld 
			sudo firewall-cmd --permanent --zone=public --add-port=80/tcp
			sudo firewall-cmd --permanent --zone=public --add-port=22/tcp
			sudo firewall-cmd --reload	
		SHELL
	end
	
	## CONFIG MACHINE WEB 1 ##
	config.vm.define "web1" do |web|
		web.vm.provision "shell", inline: <<-SHELL
			sudo yum update -y
			sudo yum install epel-release -y
			sudo yum install nginx sshpass -y
			sudo sed -i "s/80/8080/g" /etc/nginx/nginx.conf
			sudo bash -c 'echo "<html><h1>Web 1</h1><p>Vous etes actuellement sur le serveur Web numero 1</html>" > /usr/share/nginx/html/index.html'
			sudo systemctl start nginx
			
			sudo bash -c 'echo "192.168.33.10 haproxy" >> /etc/hosts'
			sudo bash -c 'echo "192.168.33.12 web2" >> /etc/hosts'
			
			sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
			sudo systemctl restart sshd
			
			ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/web1 -q -N ""
			
			sudo systemctl start firewalld 
			sudo firewall-cmd --permanent --zone=internal --add-source=192.168.33.10
			sudo firewall-cmd --permanent --zone=internal  --add-port=8080/tcp
			sudo firewall-cmd --permanent --zone=public --add-port=22/tcp
			sudo firewall-cmd --reload	
		SHELL
    end
	
	
	## CONFIG MACHINE WEB 2 ##
	config.vm.define "web2" do |web|
		web.vm.provision "shell", inline: <<-SHELL
			sudo yum update -y
			sudo yum install epel-release -y
			sudo yum install nginx sshpass -y
			sudo sed -i "s/80/8080/g" /etc/nginx/nginx.conf
			sudo bash -c 'echo "<html><h1>Web 2</h1><p>Vous etes actuellement sur le serveur Web numero 2</html>" > /usr/share/nginx/html/index.html'
			sudo systemctl start nginx
			
			sudo bash -c 'echo "192.168.33.10 haproxy" >> /etc/hosts'
			sudo bash -c 'echo "192.168.33.11 web1" >> /etc/hosts'
			
			sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
			sudo systemctl restart sshd
			
			ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/web2 -q -N ""
			
			## CLE WEB2 vers WEB1 & HA ##
			sudo sshpass -p "vagrant" ssh-copy-id -i /home/vagrant/.ssh/web2.pub -o StrictHostKeyChecking=no vagrant@web1
			sudo sshpass -p "vagrant" ssh-copy-id -i /home/vagrant/.ssh/web2.pub -o StrictHostKeyChecking=no vagrant@haproxy
			
			## CLE WEB1 vers WEB2 & HA ##
			sudo ssh -i /home/vagrant/.ssh/web2 -o StrictHostKeyChecking=no vagrant@web1 "sudo sshpass -p 'vagrant' ssh-copy-id -i /home/vagrant/.ssh/web1.pub -o StrictHostKeyChecking=no vagrant@web2 \
			&& sudo sshpass -p 'vagrant' ssh-copy-id -i /home/vagrant/.ssh/web1.pub -o StrictHostKeyChecking=no vagrant@haproxy"
			
			## CLE HA vers WEB1 & WEB2 ##
			sudo ssh -i /home/vagrant/.ssh/web2 -o StrictHostKeyChecking=no vagrant@haproxy "sudo sshpass -p 'vagrant' ssh-copy-id -i /home/vagrant/.ssh/haproxy.pub -o StrictHostKeyChecking=no vagrant@web1 \
			&& sudo sshpass -p 'vagrant' ssh-copy-id -i /home/vagrant/.ssh/haproxy.pub -o StrictHostKeyChecking=no vagrant@web2"
			
			sudo systemctl start firewalld 
			sudo firewall-cmd --permanent --zone=internal --add-source=192.168.33.10
			sudo firewall-cmd --permanent --zone=internal  --add-port=8080/tcp
			sudo firewall-cmd --permanent --zone=public --add-port=22/tcp
			sudo firewall-cmd --reload	
		SHELL
    end
end